/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface LplLanding {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLplLandingElement extends Components.LplLanding, HTMLStencilElement {
    }
    var HTMLLplLandingElement: {
        prototype: HTMLLplLandingElement;
        new (): HTMLLplLandingElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "lpl-landing": HTMLLplLandingElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface LplLanding {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "lpl-landing": LplLanding;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "lpl-landing": LocalJSX.LplLanding & JSXBase.HTMLAttributes<HTMLLplLandingElement>;
        }
    }
}
