/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface LplDl {
        "pro": Boolean;
    }
    interface LplLanding {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLplDlElement extends Components.LplDl, HTMLStencilElement {
    }
    var HTMLLplDlElement: {
        prototype: HTMLLplDlElement;
        new (): HTMLLplDlElement;
    };
    interface HTMLLplLandingElement extends Components.LplLanding, HTMLStencilElement {
    }
    var HTMLLplLandingElement: {
        prototype: HTMLLplLandingElement;
        new (): HTMLLplLandingElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "lpl-dl": HTMLLplDlElement;
        "lpl-landing": HTMLLplLandingElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface LplDl {
        "pro"?: Boolean;
    }
    interface LplLanding {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "lpl-dl": LplDl;
        "lpl-landing": LplLanding;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "lpl-dl": LocalJSX.LplDl & JSXBase.HTMLAttributes<HTMLLplDlElement>;
            "lpl-landing": LocalJSX.LplLanding & JSXBase.HTMLAttributes<HTMLLplLandingElement>;
        }
    }
}
